### ISSUE TITLE
Check for Anagram of string

### ISSUE THREAD

**Issue by Subhas-08** [Subhas-08/Basic_cpp#23]

**Comment by Jeevesh-Joshi** [comment]
Hey! I would like to contribute.

**Comment by BabesGotByte** [comment]
Hey I would like to solve this in c++ .

**Comment by BabesGotByte** [comment]
Hey!! Check my pull request #31 for this issue.

**Comment by Subhas-08** [comment]
@Jeevesh-Joshi  sorry someone add  PR for this one
