### ISSUE TITLE
Sort an array of 0s, 1s and 2s 

### ISSUE THREAD

**Issue by Prod-IP** [Subhas-08/Basic_cpp#4]

**Comment by Prod-IP** [comment]
can I work on this one ?

**Comment by ayu16** [comment]
please can you assign this to me, I would like to contribute

**Comment by Subhas-08** [comment]
@Prodip-Kumar-Paul  go ahead

**Comment by Subhas-08** [comment]
@ayu16  sorry this issue is closed add a new issue
