### ISSUE TITLE
Max Sum Contiguous Subarray 

### ISSUE THREAD

**Issue by vaishnavijha** [Subhas-08/Basic_cpp#8]
this questions is Asked in:   Facebook Paypal Yahoo Microsoft LinkedIn Amazon Goldman Sachs so thought of adding this issue and contributing to it.

**Comment by vaishnavijha** [comment]
Can this issue be assigned to me ? If you think it will make this repo better by adding this ?

**Comment by Subhas-08** [comment]
@vaishnavijha go ahead

**Comment by vaishnavijha** [comment]
Added my pull request
